name: Build and Publish on Release

on:
  release:
    types: 
      - published

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    #environment: release

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          
      - run: npm install -g pnpm
        
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Set version from release
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "Setting package version to $VERSION"
          pnpm version $VERSION --no-git-tag-version
        
      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish --no-git-checks --access public
